use Administrator;
go
CREATE SCHEMA geo AUTHORIZATION dbo;

go
CREATE TABLE geo.countries (
    id INT PRIMARY KEY,
    country_name NVARCHAR(100),
    country_sh_name NVARCHAR(10)
);
go
INSERT INTO geo.countries (id, country_name, country_sh_name) VALUES (1, 'Afghanistan', 'AF');
INSERT INTO geo.countries (id, country_name, country_sh_name) VALUES (2, 'Albania', 'AL');
INSERT INTO geo.countries (id, country_name, country_sh_name) VALUES (3, 'Algeria', 'DZ');
INSERT INTO geo.countries (id, country_name, country_sh_name) VALUES (4, 'Andorra', 'AD');
INSERT INTO geo.countries (id, country_name, country_sh_name) VALUES (5, 'Angola', 'AO');
INSERT INTO geo.countries (id, country_name, country_sh_name) VALUES (6, 'Antigua and Barbuda', 'AG');
INSERT INTO geo.countries (id, country_name, country_sh_name) VALUES (7, 'Argentina', 'AR');
INSERT INTO geo.countries (id, country_name, country_sh_name) VALUES (8, 'Armenia', 'AM');
INSERT INTO geo.countries (id, country_name, country_sh_name) VALUES (9, 'Australia', 'AU');
INSERT INTO geo.countries (id, country_name, country_sh_name) VALUES (10, 'Austria', 'AT');
INSERT INTO geo.countries (id, country_name, country_sh_name) VALUES (11, 'Azerbaijan', 'AZ');
INSERT INTO geo.countries (id, country_name, country_sh_name) VALUES (12, 'Bahamas', 'BS');
INSERT INTO geo.countries (id, country_name, country_sh_name) VALUES (13, 'Bahrain', 'BH');
INSERT INTO geo.countries (id, country_name, country_sh_name) VALUES (14, 'Bangladesh', 'BD');
INSERT INTO geo.countries (id, country_name, country_sh_name) VALUES (15, 'Barbados', 'BB');
INSERT INTO geo.countries (id, country_name, country_sh_name) VALUES (16, 'Belarus', 'BY');
INSERT INTO geo.countries (id, country_name, country_sh_name) VALUES (17, 'Belgium', 'BE');
INSERT INTO geo.countries (id, country_name, country_sh_name) VALUES (18, 'Belize', 'BZ');
INSERT INTO geo.countries (id, country_name, country_sh_name) VALUES (19, 'Benin', 'BJ');
INSERT INTO geo.countries (id, country_name, country_sh_name) VALUES (20, 'Bhutan', 'BT');
INSERT INTO geo.countries (id, country_name, country_sh_name) VALUES (21, 'Bolivia', 'BO');
INSERT INTO geo.countries (id, country_name, country_sh_name) VALUES (22, 'Bosnia and Herzegovina', 'BA');
INSERT INTO geo.countries (id, country_name, country_sh_name) VALUES (23, 'Botswana', 'BW');
INSERT INTO geo.countries (id, country_name, country_sh_name) VALUES (24, 'Brazil', 'BR');
INSERT INTO geo.countries (id, country_name, country_sh_name) VALUES (25, 'Brunei', 'BN');
INSERT INTO geo.countries (id, country_name, country_sh_name) VALUES (26, 'Bulgaria', 'BG');
INSERT INTO geo.countries (id, country_name, country_sh_name) VALUES (27, 'Burkina Faso', 'BF');
INSERT INTO geo.countries (id, country_name, country_sh_name) VALUES (28, 'Burundi', 'BI');
INSERT INTO geo.countries (id, country_name, country_sh_name) VALUES (29, 'Cabo Verde', 'CV');
INSERT INTO geo.countries (id, country_name, country_sh_name) VALUES (30, 'Cambodia', 'KH');
INSERT INTO geo.countries (id, country_name, country_sh_name) VALUES (31, 'Cameroon', 'CM');
INSERT INTO geo.countries (id, country_name, country_sh_name) VALUES (32, 'Canada', 'CA');
INSERT INTO geo.countries (id, country_name, country_sh_name) VALUES (33, 'Central African Republic', 'CF');
INSERT INTO geo.countries (id, country_name, country_sh_name) VALUES (34, 'Chad', 'TD');
INSERT INTO geo.countries (id, country_name, country_sh_name) VALUES (35, 'Chile', 'CL');
INSERT INTO geo.countries (id, country_name, country_sh_name) VALUES (36, 'China', 'CN');
INSERT INTO geo.countries (id, country_name, country_sh_name) VALUES (37, 'Colombia', 'CO');
INSERT INTO geo.countries (id, country_name, country_sh_name) VALUES (38, 'Comoros', 'KM');
INSERT INTO geo.countries (id, country_name, country_sh_name) VALUES (39, 'Congo (Congo-Brazzaville)', 'CG');
INSERT INTO geo.countries (id, country_name, country_sh_name) VALUES (40, 'Costa Rica', 'CR');
INSERT INTO geo.countries (id, country_name, country_sh_name) VALUES (41, 'Croatia', 'HR');
INSERT INTO geo.countries (id, country_name, country_sh_name) VALUES (42, 'Cuba', 'CU');
INSERT INTO geo.countries (id, country_name, country_sh_name) VALUES (43, 'Cyprus', 'CY');
INSERT INTO geo.countries (id, country_name, country_sh_name) VALUES (44, 'Czech Republic (Czechia)', 'CZ');
INSERT INTO geo.countries (id, country_name, country_sh_name) VALUES (45, 'Democratic Republic of the Congo', 'CD');
INSERT INTO geo.countries (id, country_name, country_sh_name) VALUES (46, 'Denmark', 'DK');
INSERT INTO geo.countries (id, country_name, country_sh_name) VALUES (47, 'Djibouti', 'DJ');
INSERT INTO geo.countries (id, country_name, country_sh_name) VALUES (48, 'Dominica', 'DM');
INSERT INTO geo.countries (id, country_name, country_sh_name) VALUES (49, 'Dominican Republic', 'DO');
INSERT INTO geo.countries (id, country_name, country_sh_name) VALUES (50, 'Ecuador', 'EC');
INSERT INTO geo.countries (id, country_name, country_sh_name) VALUES (51, 'Egypt', 'EG');
INSERT INTO geo.countries (id, country_name, country_sh_name) VALUES (52, 'El Salvador', 'SV');
INSERT INTO geo.countries (id, country_name, country_sh_name) VALUES (53, 'Equatorial Guinea', 'GQ');
INSERT INTO geo.countries (id, country_name, country_sh_name) VALUES (54, 'Eritrea', 'ER');
INSERT INTO geo.countries (id, country_name, country_sh_name) VALUES (55, 'Estonia', 'EE');
INSERT INTO geo.countries (id, country_name, country_sh_name) VALUES (56, 'Eswatini (fmr. "Swaziland")', 'SZ');
INSERT INTO geo.countries (id, country_name, country_sh_name) VALUES (57, 'Ethiopia', 'ET');
INSERT INTO geo.countries (id, country_name, country_sh_name) VALUES (58, 'Fiji', 'FJ');
INSERT INTO geo.countries (id, country_name, country_sh_name) VALUES (59, 'Finland', 'FI');
INSERT INTO geo.countries (id, country_name, country_sh_name) VALUES (60, 'France', 'FR');
INSERT INTO geo.countries (id, country_name, country_sh_name) VALUES (61, 'Gabon', 'GA');
INSERT INTO geo.countries (id, country_name, country_sh_name) VALUES (62, 'Gambia', 'GM');
INSERT INTO geo.countries (id, country_name, country_sh_name) VALUES (63, 'Georgia', 'GE');
INSERT INTO geo.countries (id, country_name, country_sh_name) VALUES (64, 'Germany', 'DE');
INSERT INTO geo.countries (id, country_name, country_sh_name) VALUES (65, 'Ghana', 'GH');
INSERT INTO geo.countries (id, country_name, country_sh_name) VALUES (66, 'Greece', 'GR');
INSERT INTO geo.countries (id, country_name, country_sh_name) VALUES (67, 'Grenada', 'GD');
INSERT INTO geo.countries (id, country_name, country_sh_name) VALUES (68, 'Guatemala', 'GT');
INSERT INTO geo.countries (id, country_name, country_sh_name) VALUES (69, 'Guinea', 'GN');
INSERT INTO geo.countries (id, country_name, country_sh_name) VALUES (70, 'Guinea-Bissau', 'GW');
INSERT INTO geo.countries (id, country_name, country_sh_name) VALUES (71, 'Guyana', 'GY');
INSERT INTO geo.countries (id, country_name, country_sh_name) VALUES (72, 'Haiti', 'HT');
INSERT INTO geo.countries (id, country_name, country_sh_name) VALUES (73, 'Honduras', 'HN');
INSERT INTO geo.countries (id, country_name, country_sh_name) VALUES (74, 'Hungary', 'HU');
INSERT INTO geo.countries (id, country_name, country_sh_name) VALUES (75, 'Iceland', 'IS');
INSERT INTO geo.countries (id, country_name, country_sh_name) VALUES (76, 'India', 'IN');
INSERT INTO geo.countries (id, country_name, country_sh_name) VALUES (77, 'Indonesia', 'ID');
INSERT INTO geo.countries (id, country_name, country_sh_name) VALUES (78, 'Iran', 'IR');
INSERT INTO geo.countries (id, country_name, country_sh_name) VALUES (79, 'Iraq', 'IQ');
INSERT INTO geo.countries (id, country_name, country_sh_name) VALUES (80, 'Ireland', 'IE');
INSERT INTO geo.countries (id, country_name, country_sh_name) VALUES (81, 'Israel', 'IL');
INSERT INTO geo.countries (id, country_name, country_sh_name) VALUES (82, 'Italy', 'IT');
INSERT INTO geo.countries (id, country_name, country_sh_name) VALUES (83, 'Jamaica', 'JM');
INSERT INTO geo.countries (id, country_name, country_sh_name) VALUES (84, 'Japan', 'JP');
INSERT INTO geo.countries (id, country_name, country_sh_name) VALUES (85, 'Jordan', 'JO');
INSERT INTO geo.countries (id, country_name, country_sh_name) VALUES (86, 'Kazakhstan', 'KZ');
INSERT INTO geo.countries (id, country_name, country_sh_name) VALUES (87, 'Kenya', 'KE');
INSERT INTO geo.countries (id, country_name, country_sh_name) VALUES (88, 'Kiribati', 'KI');
INSERT INTO geo.countries (id, country_name, country_sh_name) VALUES (89, 'Kuwait', 'KW');
INSERT INTO geo.countries (id, country_name, country_sh_name) VALUES (90, 'Kyrgyzstan', 'KG');
INSERT INTO geo.countries (id, country_name, country_sh_name) VALUES (91, 'Laos', 'LA');
INSERT INTO geo.countries (id, country_name, country_sh_name) VALUES (92, 'Latvia', 'LV');
INSERT INTO geo.countries (id, country_name, country_sh_name) VALUES (93, 'Lebanon', 'LB');
INSERT INTO geo.countries (id, country_name, country_sh_name) VALUES (94, 'Lesotho', 'LS');
INSERT INTO geo.countries (id, country_name, country_sh_name) VALUES (95, 'Liberia', 'LR');
INSERT INTO geo.countries (id, country_name, country_sh_name) VALUES (96, 'Libya', 'LY');
INSERT INTO geo.countries (id, country_name, country_sh_name) VALUES (97, 'Liechtenstein', 'LI');
INSERT INTO geo.countries (id, country_name, country_sh_name) VALUES (98, 'Lithuania', 'LT');
INSERT INTO geo.countries (id, country_name, country_sh_name) VALUES (99, 'Luxembourg', 'LU');
INSERT INTO geo.countries (id, country_name, country_sh_name) VALUES (100, 'Madagascar', 'MG');
INSERT INTO geo.countries (id, country_name, country_sh_name) VALUES (101, 'Malawi', 'MW');
INSERT INTO geo.countries (id, country_name, country_sh_name) VALUES (102, 'Malaysia', 'MY');
INSERT INTO geo.countries (id, country_name, country_sh_name) VALUES (103, 'Maldives', 'MV');
INSERT INTO geo.countries (id, country_name, country_sh_name) VALUES (104, 'Mali', 'ML');
INSERT INTO geo.countries (id, country_name, country_sh_name) VALUES (105, 'Malta', 'MT');
INSERT INTO geo.countries (id, country_name, country_sh_name) VALUES (106, 'Marshall Islands', 'MH');
INSERT INTO geo.countries (id, country_name, country_sh_name) VALUES (107, 'Mauritania', 'MR');
INSERT INTO geo.countries (id, country_name, country_sh_name) VALUES (108, 'Mauritius', 'MU');
INSERT INTO geo.countries (id, country_name, country_sh_name) VALUES (109, 'Mexico', 'MX');
INSERT INTO geo.countries (id, country_name, country_sh_name) VALUES (110, 'Micronesia', 'FM');
INSERT INTO geo.countries (id, country_name, country_sh_name) VALUES (111, 'Moldova', 'MD');
INSERT INTO geo.countries (id, country_name, country_sh_name) VALUES (112, 'Monaco', 'MC');
INSERT INTO geo.countries (id, country_name, country_sh_name) VALUES (113, 'Mongolia', 'MN');
INSERT INTO geo.countries (id, country_name, country_sh_name) VALUES (114, 'Montenegro', 'ME');
INSERT INTO geo.countries (id, country_name, country_sh_name) VALUES (115, 'Morocco', 'MA');
INSERT INTO geo.countries (id, country_name, country_sh_name) VALUES (116, 'Mozambique', 'MZ');
INSERT INTO geo.countries (id, country_name, country_sh_name) VALUES (117, 'Myanmar (formerly Burma)', 'MM');
INSERT INTO geo.countries (id, country_name, country_sh_name) VALUES (118, 'Namibia', 'NA');
INSERT INTO geo.countries (id, country_name, country_sh_name) VALUES (119, 'Nauru', 'NR');
INSERT INTO geo.countries (id, country_name, country_sh_name) VALUES (120, 'Nepal', 'NP');
INSERT INTO geo.countries (id, country_name, country_sh_name) VALUES (121, 'Netherlands', 'NL');
INSERT INTO geo.countries (id, country_name, country_sh_name) VALUES (122, 'New Zealand', 'NZ');
INSERT INTO geo.countries (id, country_name, country_sh_name) VALUES (123, 'Nicaragua', 'NI');
INSERT INTO geo.countries (id, country_name, country_sh_name) VALUES (124, 'Niger', 'NE');
INSERT INTO geo.countries (id, country_name, country_sh_name) VALUES (125, 'Nigeria', 'NG');
INSERT INTO geo.countries (id, country_name, country_sh_name) VALUES (126, 'North Korea', 'KP');
INSERT INTO geo.countries (id, country_name, country_sh_name) VALUES (127, 'North Macedonia', 'MK');
INSERT INTO geo.countries (id, country_name, country_sh_name) VALUES (128, 'Norway', 'NO');
INSERT INTO geo.countries (id, country_name, country_sh_name) VALUES (129, 'Oman', 'OM');
INSERT INTO geo.countries (id, country_name, country_sh_name) VALUES (130, 'Pakistan', 'PK');
INSERT INTO geo.countries (id, country_name, country_sh_name) VALUES (131, 'Palau', 'PW');
INSERT INTO geo.countries (id, country_name, country_sh_name) VALUES (132, 'Palestine State', 'PS');
INSERT INTO geo.countries (id, country_name, country_sh_name) VALUES (133, 'Panama', 'PA');
INSERT INTO geo.countries (id, country_name, country_sh_name) VALUES (134, 'Papua New Guinea', 'PG');
INSERT INTO geo.countries (id, country_name, country_sh_name) VALUES (135, 'Paraguay', 'PY');
INSERT INTO geo.countries (id, country_name, country_sh_name) VALUES (136, 'Peru', 'PE');
INSERT INTO geo.countries (id, country_name, country_sh_name) VALUES (137, 'Philippines', 'PH');
INSERT INTO geo.countries (id, country_name, country_sh_name) VALUES (138, 'Poland', 'PL');
INSERT INTO geo.countries (id, country_name, country_sh_name) VALUES (139, 'Portugal', 'PT');
INSERT INTO geo.countries (id, country_name, country_sh_name) VALUES (140, 'Qatar', 'QA');
INSERT INTO geo.countries (id, country_name, country_sh_name) VALUES (141, 'Romania', 'RO');
INSERT INTO geo.countries (id, country_name, country_sh_name) VALUES (142, 'Russia', 'RU');
INSERT INTO geo.countries (id, country_name, country_sh_name) VALUES (143, 'Rwanda', 'RW');
INSERT INTO geo.countries (id, country_name, country_sh_name) VALUES (144, 'Saint Kitts and Nevis', 'KN');
INSERT INTO geo.countries (id, country_name, country_sh_name) VALUES (145, 'Saint Lucia', 'LC');
INSERT INTO geo.countries (id, country_name, country_sh_name) VALUES (146, 'Saint Vincent and the Grenadines', 'VC');
INSERT INTO geo.countries (id, country_name, country_sh_name) VALUES (147, 'Samoa', 'WS');
INSERT INTO geo.countries (id, country_name, country_sh_name) VALUES (148, 'San Marino', 'SM');
INSERT INTO geo.countries (id, country_name, country_sh_name) VALUES (149, 'Sao Tome and Principe', 'ST');
INSERT INTO geo.countries (id, country_name, country_sh_name) VALUES (150, 'Saudi Arabia', 'SA');
INSERT INTO geo.countries (id, country_name, country_sh_name) VALUES (151, 'Senegal', 'SN');
INSERT INTO geo.countries (id, country_name, country_sh_name) VALUES (152, 'Serbia', 'RS');
INSERT INTO geo.countries (id, country_name, country_sh_name) VALUES (153, 'Seychelles', 'SC');
INSERT INTO geo.countries (id, country_name, country_sh_name) VALUES (154, 'Sierra Leone', 'SL');
INSERT INTO geo.countries (id, country_name, country_sh_name) VALUES (155, 'Singapore', 'SG');
INSERT INTO geo.countries (id, country_name, country_sh_name) VALUES (156, 'Slovakia', 'SK');
INSERT INTO geo.countries (id, country_name, country_sh_name) VALUES (157, 'Slovenia', 'SI');
INSERT INTO geo.countries (id, country_name, country_sh_name) VALUES (158, 'Solomon Islands', 'SB');
INSERT INTO geo.countries (id, country_name, country_sh_name) VALUES (159, 'Somalia', 'SO');
INSERT INTO geo.countries (id, country_name, country_sh_name) VALUES (160, 'South Africa', 'ZA');
INSERT INTO geo.countries (id, country_name, country_sh_name) VALUES (161, 'South Korea', 'KR');
INSERT INTO geo.countries (id, country_name, country_sh_name) VALUES (162, 'South Sudan', 'SS');
INSERT INTO geo.countries (id, country_name, country_sh_name) VALUES (163, 'Spain', 'ES');
INSERT INTO geo.countries (id, country_name, country_sh_name) VALUES (164, 'Sri Lanka', 'LK');
INSERT INTO geo.countries (id, country_name, country_sh_name) VALUES (165, 'Sudan', 'SD');
INSERT INTO geo.countries (id, country_name, country_sh_name) VALUES (166, 'Suriname', 'SR');
INSERT INTO geo.countries (id, country_name, country_sh_name) VALUES (167, 'Sweden', 'SE');
INSERT INTO geo.countries (id, country_name, country_sh_name) VALUES (168, 'Switzerland', 'CH');
INSERT INTO geo.countries (id, country_name, country_sh_name) VALUES (169, 'Syria', 'SY');
INSERT INTO geo.countries (id, country_name, country_sh_name) VALUES (170, 'Tajikistan', 'TJ');
INSERT INTO geo.countries (id, country_name, country_sh_name) VALUES (171, 'Tanzania', 'TZ');
INSERT INTO geo.countries (id, country_name, country_sh_name) VALUES (172, 'Thailand', 'TH');
INSERT INTO geo.countries (id, country_name, country_sh_name) VALUES (173, 'Timor-Leste', 'TL');
INSERT INTO geo.countries (id, country_name, country_sh_name) VALUES (174, 'Togo', 'TG');
INSERT INTO geo.countries (id, country_name, country_sh_name) VALUES (175, 'Tonga', 'TO');
INSERT INTO geo.countries (id, country_name, country_sh_name) VALUES (176, 'Trinidad and Tobago', 'TT');
INSERT INTO geo.countries (id, country_name, country_sh_name) VALUES (177, 'Tunisia', 'TN');
INSERT INTO geo.countries (id, country_name, country_sh_name) VALUES (178, 'Turkey', 'TR');
INSERT INTO geo.countries (id, country_name, country_sh_name) VALUES (179, 'Turkmenistan', 'TM');
INSERT INTO geo.countries (id, country_name, country_sh_name) VALUES (180, 'Tuvalu', 'TV');
INSERT INTO geo.countries (id, country_name, country_sh_name) VALUES (181, 'Uganda', 'UG');
INSERT INTO geo.countries (id, country_name, country_sh_name) VALUES (182, 'Ukraine', 'UA');
INSERT INTO geo.countries (id, country_name, country_sh_name) VALUES (183, 'United Arab Emirates', 'AE');
INSERT INTO geo.countries (id, country_name, country_sh_name) VALUES (184, 'United Kingdom', 'GB');
INSERT INTO geo.countries (id, country_name, country_sh_name) VALUES (185, 'United States of America', 'US');
INSERT INTO geo.countries (id, country_name, country_sh_name) VALUES (186, 'Uruguay', 'UY');
INSERT INTO geo.countries (id, country_name, country_sh_name) VALUES (187, 'Uzbekistan', 'UZ');
INSERT INTO geo.countries (id, country_name, country_sh_name) VALUES (188, 'Vanuatu', 'VU');
INSERT INTO geo.countries (id, country_name, country_sh_name) VALUES (189, 'Vatican City', 'VA');
INSERT INTO geo.countries (id, country_name, country_sh_name) VALUES (190, 'Venezuela', 'VE');
INSERT INTO geo.countries (id, country_name, country_sh_name) VALUES (191, 'Vietnam', 'VN');
INSERT INTO geo.countries (id, country_name, country_sh_name) VALUES (192, 'Yemen', 'YE');
INSERT INTO geo.countries (id, country_name, country_sh_name) VALUES (193, 'Zambia', 'ZM');
INSERT INTO geo.countries (id, country_name, country_sh_name) VALUES (194, 'Zimbabwe', 'ZW');